### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rafaelquint**

### CODE REVIEW

**Comment by Daniel-Pivonka** [comment]
please sign off your commits

**Review by adk3798 — CHANGES_REQUESTED** [review]
:angry:

**Comment by timflannagan** [comment]
thank you - this is a much needed PR!

**Comment by nathan-weinberg** [comment]
PR does not align with style guidelines, lacks description

**Comment by timflannagan** [comment]
@nathan-weinberg one could argue there's a distinct lack of a `CONTRIBUTORS.md` file, which would detail that there needs to be a description in the body of a PR.

I urge you to re-open this.

**Comment by nathan-weinberg** [comment]
@timflannagan1 Thank you for the feedback; I would welcome a PR adding a `CONTRIBUTORS.md` file

**Comment by rafaelquint** [comment]
> @timflannagan1 Thank you for the feedback; I would welcome a PR adding a `CONTRIBUTORS.md` file

https://github.com/nathan-weinberg/bash-scripts/pull/4

PR has been made -- Please view!

**Pull request closed without merging**
